### ISSUE TITLE
Add timeout for rate limit retries 

### ISSUE THREAD

**Issue by drorbar** [facetoe/zenpy#109]
Hi,

Love the fact you added the rate limit feature but wanted to ask if you could please add a timeout for the sleeping processing.
Currently, if too much time passed without being able to get info from the zendesk I have nothing to do but wait for the system to finish sleeping over and over again.
I would love if I could send a timeout to the system and if it reach this an exception will be raised 

Thanks

**Comment by facetoe** [comment]
HI @drorbar, could you provide a little more info on what you are trying to achieve? I'm not sure I understand your problem well enough to implement a solution.

**Comment by drorbar** [comment]
@facetoe sure,
I wrote a program which runs periodically and combines data from several sources together before sending it to a database.
One of my data sources is zendesk, and I am using zenpy to get the data I need. The problem I'm facing is that when I reach the rate-limit of zendesk it starts sleeping over and over (sometimes for a couple of minutes when the zendesk is really busy).
I would rather have my database filled with partial data (without the zendesk info) than waiting a long time between different runs of my program.
To do so I need zenpy to sleep on rate-limit error for a max amount of time and then send some kind of exception to the program using it.

If I missed something or it is already implemented somehow in zenpy I would love to know :)

**Comment by facetoe** [comment]
OK I see what you mean. Is the time you are willing to wait relatively constant? If so you could use SIGALARM to throw an exception if Zenpy hasn't completed within a certain time. There is an example here - https://docs.python.org/2/library/signal.html#example. Would that work for you?

**Comment by drorbar** [comment]
Hi, 

The wait time is pretty constant and the SIGALARM could be a solution.
If I understand it correctly it will not allow me to know if the time passed cause I got a rate-limit issue or if I just have too many items to read from the zendesk and it taking time - which might mean I'll never receive information from zendesk cause I'll alway wait for too many items which take more time than the SIGALARM.

**Comment by facetoe** [comment]
Yes this is correct, the SIGALARM solution doesn't help with determining whether or not the wait is due to a large number of items or rate limiting. I'll need to think about this a bit more but two ideas come to mind:

- A rate limit budget that will raise some exception when the budget is spent (time based)
- A max rate limit value that will throw an exception when decremented to zero (event based)

There are probably other possible solutions as well. Unfortunately I won't have much time to work on Zenpy for the next few weeks, however I will have a good chunk of time coming up in the next month or so. I will try to get to it before then but in the worst case it will be a little over a month before I can get to this.

**Comment by drorbar** [comment]
Both solutions sound great, I would rather have the time-based but the event-based could be good enough for me 

thx a lot

**Comment by facetoe** [comment]
Hi @drorbar, I've implemented the `ratelimit_budget` feature (http://docs.facetoe.com.au/zenpy.html#rate-limiting). Let me know if you have any issues!

**Comment by drorbar** [comment]
@facetoe yes! thank you!
