### ISSUE TITLE
Export large ticket metrics

### ISSUE THREAD

**Issue by inmorales** [facetoe/zenpy#180]
Hello Facetoe

Do you know how I can export all the ticket_metrics of tickets? 
I have a python script that bring ticket with incremental export (1000 tickets at once) and I do not understand the incremental metric export. When I tried to call one "zenpy_client.tickets.metrics(ticket_id=<tricket_id>)" for each ticket in each package, this spend about 17 min by 1000 tickets. This is a lot of time because in my company create more than 300.000 tickets per day. 

Best Regards

**Comment by inmorales** [comment]
I just understand that "zenpy_client.ticket_metrics()" can help, but there are no bibliography abaut this object or endpoint. Do you know How can I do something similat to incremental ticket with this? I mean something with date.
The problem with the incremental ticketmetric is that this no give the metrics of a ticket. These call give me just the modification and I do not understand how use it.

**Comment by facetoe** [comment]
Hi @inmorales, 

Yes with that sort of volume the `zenpy_client.tickets.metrics` approach will take forever. Have you looked at the incremental Ticket Metric Events endpoint - https://developer.zendesk.com/rest_api/docs/core/ticket_metric_events?

You can access this in Zenpy as follows:

```python
start_time = datetime.datetime.now() - datetime.timedelta(days=1)
for metric in zenpy_client.tickets.metrics_incremental(start_time):
    print(metric.to_dict())
```

This endpoint should be much faster to query.

Hope this helps!

**Comment by inmorales** [comment]
I tried this, but I do not undestand how use it. Because I think that this endpoint comes with ticket metric event and I don't know how use it.

**Comment by facetoe** [comment]
Well I'm not sure how I can help as I don't know what you are trying to achieve.

**Comment by inmorales** [comment]
I would like to achieve a list or dict with this information:
ticket_id
created
updated
reopens
replies
assignee_update
requester_updated
status_updated
initially_assigned
assigned
solved
latest_comment_added
reply_time_in_minutes
first_resolution_time_in_minutes
full_resolution_time_in_minutes
agent_wait_time_in_minutes
requester_wait_time_in_minutes
on_hold_time_in_minutes

**Comment by facetoe** [comment]
It doesn't look like the incremental Ticket Metric Events provide all that information, so you're out of luck. Maybe get in touch with Zendesk and see if they can suggest a way to get this information without querying Ticket Metrics for each ticket.

**Comment by jjjchens235** [comment]
I spent a lot of time trying to figure this out and finally found a solution that worked for me using the Zenpy library.

The Zendesk API supports something called side-loading. Here's an [example](https://stackoverflow.com/a/57274209) of the raw API call. Basically, when you pull in `tickets`, you can 'sideload' all the `ticket_metrics` associated with each ticket you pulled in. Since tickets is an incremental endpoint, you're able to load ticket_metrics incrementally as well.

Luckily, Zenpy also supports this as well. This is what Zenpy's [documentation](http://docs.facetoe.com.au/zenpy.html#side-loading) has to say on sideloading.

Ultimately you want to do something like this:
```py
response_generator = zenpy_client.tickets(include='metric_sets')
```
