### ISSUE TITLE
Having trouble changing the job status

### ISSUE THREAD

**Issue by erobert98** [facetoe/zenpy#257]
I'm having trouble figuring out how to change the job status, i found this in the library 

self.job_status = Api(config, object_type='job_status', endpoint=EndpointFactory('job_statuses')), 

and in that vein i tried this,

ticket = zenpy_client.tickets(id= ticketID)
ticket.status.(update, extend, append)('resolved')  --- not all at once but individually
zenpy_client.tickets.update(ticket)

to no avail any help?

**Comment by erobert98** [comment]
ticket = zenpy_client.tickets(id= ticketID)
ticket.status = 'solved' 
zenpy_client.tickets.update(ticket)

returns error 'zenpy.lib.exception.APIException, {"error": "RecordInvalid", "description": "Record validation errors", "details": {"base": [{"description": "Type of Content: \u00e9 necess\u00e1rio(a) para resolver um ticket", "error": null, "ticket_field_id": 360008591391, "ticket_field_type": "FieldTagger"}]}}'

**Comment by facetoe** [comment]
Hi @erobert98, 

As you might have discovered already, the job_status endpoint is used for getting progress information on large batch jobs (https://developer.zendesk.com/rest_api/docs/core/job_statuses), so not what you want.

Your last comment looks about right, however from the looks of the Exception it appears that you have a ticket field that cannot be null. What happens if you try to set that same ticket to `solved` in the interface?
