### ISSUE TITLE
jira_links API generator no longer respects ticket_id or issue_id

### ISSUE THREAD

**Issue by mvforgione** [facetoe/zenpy#400]
When querying for all jira_links with a specific ticket_id or issue_id, the resultant generator no longer respects the ticket_id or issue_id param in subsequent calls. It appears that it appends the since_id parameter when paging through results while removing the previous ticket_id or issue_id.

`    def get_next_page(self, page_num=None, page_size=None):
        try:
            url = self._response_json['links'][-1]['url']
            url = re.sub('/\d+', '', url)
            params = {'since_id': self._response_json['links'][-1]['id']}
            response = self.response_handler.api._get(url, raw_response=True, params=params)
            return response.json()
        except (IndexError, KeyError):
            raise StopIteration()`

This results in retrieving the matched links on the first call, but then retrieving many more unrelated jira_links thereafter.

**Comment by mvforgione** [comment]
This seems to be related to #389

**Comment by facetoe** [comment]
I can't really test this as have no Jira so if anyone is able to submit a patch for this it would be greatly appreciated.

**Comment by jwalterclark** [comment]
I'm happy to take a pass at this since I created that PR. Before #389 there simply was no generator for Jira links. The other endpoints are helpful and provide a fully formed next page link (with params).

For example, `include=comment_count` carries over into `next_page`.

```
curl 'https://{subdomain}.zendesk.com/api/v2/tickets.json?include=comment_count' -u user:pass | jq

{
  "tickets": [
    {
      "url": "https://{subdomain}.zendesk.com/api/v2/tickets/234.json",
      # ... snip ...
      "allow_attachments": true
    }
  ],
  "next_page": "https://{subdomain}.zendesk.com/api/v2/tickets.json?include=comment_count&page=2",
  "previous_page": null,
  "count": 1475
}
```

The Jira Links response doesn't have this so I'll have to take some time and get my head wrapped around the request/response handlers in the API library.

```
curl 'https://{subdomain}.zendesk.com/api/services/jira/links?limit=1' -u user:pass | jq

{
  "links": [
    {
      "id": 123,
      "ticket_id": "234",
      "issue_id": "345",
      "issue_key": "A-1",
      "url": "https://agari.zendesk.com/api/services/jira/links/123",
      "created_at": "2017-11-01T12:03:49.000Z",
      "updated_at": "2017-11-01T12:03:49.000Z"
    }
  ],
  "total": 1750
}
```

As far as I can tell the generator only gets the JSON response, but maybe there's a way to drill down to the original request `endpoint_args`/`endpoint_kwargs`?
