### ISSUE TITLE
zenpy.user.create_or_update users appears to be erroring?

### ISSUE THREAD

**Issue by akshya-qwickly** [facetoe/zenpy#531]
We use Zenpy to generate user tickets from our platform.

We recently updated to Zenpy 2.0.25 and we think we've come across a bug,

the function zenpy.user.create_or_update appears to be creating a new user even if a user with the same email already exists. The User object is initialized with a name, an email (and with/without verified=True, same results)

This is causing issues for us since any new tickets created are getting a New User assigned to it (and this new user is not getting an email set, since that email already "exists"), so people are not getting notifications.

Any help you can provide is appreciated, this is causing quite some issues for us.

**Comment by Qwickly** [comment]
Quick update, we ended up reverting back to the last stable version of Zenpy we were running (1.2.3) and the features are working as expected once more. 

My other thought is that obviously the objects and functions I used in the 1.2.3 package may have been deprecated in the 2.0.25 package, but I didn't see any errors, or notes in the documentation stating that.

**Comment by ahmedsabriz** [comment]
Hi @Qwickly ,
I am unable to reproduce this. It is not possible for two users to share an email address since it is a unique id enforced server side. Can you please share a snippet of your code?

**Comment by ahmedsabriz** [comment]
Hi @akshya-qwickly,
Sorry for the late reply. No new user is created. It just updates the old user with the new name (if different) and verifies the email address if unverified. You can double check by taking note of the user id.

**Comment by C0deZLee** [comment]
Same thing happening to us

**Comment by ahmedsabriz** [comment]
Hi @C0deZLee can you share more details on what you are experiencing? perhaps a screenshot of the user before and after you run your code?

**Comment by cryptomail** [comment]
This is very interesting.  I would strongly suggest you employ the simple ticket creation process and NOT employ pre-creating the user.  Ticket creation will take user fields and vivify a user if need be.  This is a nicety that we have afforded within the ticket api.
Please let me know if that works.
Posting some sample code here: https://gist.github.com/cryptomail/f40a3c40690e6296031851a6385061d2

This **MAY** solve your issue but my interest is piqued as to why you're experiencing this issue.
Looking into it.

Finally, thank you so much for using the Zendesk API and the Zendesk system(s).  We appreciate it.  Again, looking forward to bringing more clarity soon.

**Comment by cryptomail** [comment]
Blah, as I suspected, it does have to do with some asynchronicity issues.  Creating the user may happen in some async way, and creating the ticket may happen in some synchronous way.  If two requests are issued, it does appear to me that the ticket request finished *first*, thus causing the original user create request to fail.
Here is the suspect line:
https://github.com/facetoe/zenpy/blob/25f005abb20bdf218998ebc66fba134078c8bcb4/zenpy/lib/request.py#L66
the user creation employs create_or_update_many with cardinality of `1`.
This is problematic because 
```create_or_update_many```
Forces asynchronous behaviour.
I will look into making a change to the library such that this does not happen if there is a singular target object.

Workarounds:
1. Allow ticket creation endpoint to vivify your user (as suggested above and in GIST)
2. Sleep wait 🤮 ugh don't do that 

Let me see if I can craft a cogent fix, but in the mean time please let me know if option 1 fixes your issue.

**Comment by cryptomail** [comment]
Actually I found root cause.  I will fix your script. [akshya-qwickly](https://github.com/akshya-qwickly)

The MAIN issue is that the script is overly aggressive in setting the requester and submitter objects.

https://gist.github.com/cryptomail/bcce855da37f8d48185375ca413d5e58

Please do not submit the entire requester object.  requester_id and submitter_id should suffice.
