### ISSUE TITLE
Couldn't upload attachment in the Zendesk using Python API Clients 

### ISSUE THREAD

**Issue by mafrul** [facetoe/zenpy#61]
I have tried with upload an attachment to Zendesk using Python Client Library by Facetoe(https://github.com/facetoe/zenpy)
But it is not working here. Please see below my source code
```
from zenpy import *
import os
creds = {
    'email' : '{email}',
    'token' : '{token}',
    'subdomain': '{subdomain}'
}
zenpy = Zenpy(**creds)

from zenpy.lib.api_objects import Ticket

from zenpy.lib.api_objects import Attachment
att=Attachment(content_type="image/png", content_url=os.getcwd()+"/test.png", file_name="test.png")
abc=zenpy.attachments.create(att)
print abc
```

Please give me a solution how can i upload an attachment in Zendesk Using Python Client API and update the ticket with attachment. Waiting for your kind response.

**Comment by facetoe** [comment]
Currently the attachment endpoint only supports reading, however it shouldn't be too hard to modify it to support pushing attachments. I will try to get to this sometime this week or on the weekend.

**Comment by facetoe** [comment]
@mafrul you can now upload attachments and associate them with a ticket with the following steps:

```python
u = zenpy.attachments.upload('/some/path/to/file.txt', filename='file.txt')
ticket = zenpy.tickets(id=8)
ticket.comment = Comment(body='Some comment', uploads=[u.token])
zenpy.tickets.update(ticket)
```

**Comment by mafrul** [comment]
Thank You so much.

**Comment by facetoe** [comment]
No problem, let me know if you find any bugs in the new feature.

**Comment by caduri** [comment]
Hi, I just researching how to upload attachments to zendesk through zenpy and link them to the comment and its not clear from the documentation

Can you please add an example or a clarification to the docs, thanks

**Comment by facetoe** [comment]
Hi @caduri, there is a snippet here that uploads an attachment - https://github.com/facetoe/zenpy#uploading-an-attachment. 

The idea is you first upload the attachment and obtain an upload instance which contains the token. You can then add a comment to the ticket along with the token you obtained previously and it will be associated with the comment.

Let me know if you have any trouble.

**Comment by caduri** [comment]
Thanks @facetoe, it's the same snippet as in this issue :)

I meant to suggest that you should add the snippet to the docs in http://docs.facetoe.com.au/zenpy.html?highlight=attachments#upload or where ever you think its appropriate

**Comment by facetoe** [comment]
Ahh, I see. Well, pull requests welcome!

**Comment by tesmerjg** [comment]
Do you happen to have an example of uploading multiple attachments? 

I'm having issues in the case of a ticket with multiple attachments and I'm not sure if its a bug or my misunderstanding of the Zenpy and the Zendesk API. 

It seems like the only way I can upload multiple files in a single comment is to include a number of different tokens (passed in as an array of tokens) to the uploads field of the Comment. It seems from the Zendesk docs that I should be able to pass in a single token representing the batch of files, so long as I re-use the token in subsequent uploads, but this never seems to work.

Basically I have a method that returns an array of Upload objects, each with its own unique token. I then create a new array of just the string tokens and use that in the upload, like this:
![image](https://user-images.githubusercontent.com/438620/36179661-31ec1366-10eb-11e8-8225-88d909b65bda.png)

The weird thing is that when I pass in a token to the Upload method, like this:
![image](https://user-images.githubusercontent.com/438620/36179733-81ee0d2e-10eb-11e8-8bf9-4c84bd6ee7dd.png)

Zendesk appends the token I pass to the filenames of the secondary attachments, AND I still have to pass in the array of tokens in order to get multiple tokens associated with a single comment.

![image](https://user-images.githubusercontent.com/438620/36179778-b9771ccc-10eb-11e8-922e-bd2ba1210b74.png)

I have this working now with the multiple tokens in an array approach, but I'd like to know if I've misunderstood the API or if I'm on the right track.

THANK YOU. :)

**Comment by sggottlieb** [comment]
Just a small tweak to the sample. The filename argument is actually "target_name"

u = zenpy_client.attachments.upload('/path/to/file.txt', target_name="file.txt")
