### ISSUE TITLE
Zopim.com deprecation

### ISSUE THREAD

**Issue by ben-lorisai** [facetoe/zenpy#658]
Looks like Zenpy's ChatApi still relies on the zopim.com endpoint though it's being deprecated by Zendesk at the end of October. Oct 29th to be precise.
Any plans for dealing with this?

**Comment by cryptomail** [comment]
> Looks like Zenpy's ChatApi still relies on the zopim.com endpoint though it's being deprecated by Zendesk at the end of October. Oct 29th to be precise. Any plans for dealing with this?

hey @ben-lorisai Thanks for reminding me.
You may be referring to this article: https://support.zendesk.com/hc/en-us/articles/7827476398362-Deprecating-the-Zopim-Chat-REST-API-domain

Seems like ZenPy better be facilitating this transition :) 
Otherwise code like [this](https://github.com/facetoe/zenpy/blob/dfb8ab3190fd042725fbd00e3714d89a0c06b4c2/zenpy/lib/api.py#L2119) will certainly break things!

Do you want to have a crack at the solve here for fun?
If not I can do it!
I refuse to see any of our customers / user suffer from this breaking change.

**Comment by ben-lorisai** [comment]
hey Joshua thanks for your response. Not sure if I will have time to deal with this so there's someone else here who will be trying several ways to deal with this including workarounds that won't require changes to the package.
Would we great though if you'll be able to do it :)

**Comment by cryptomail** [comment]
> hey Joshua thanks for your response. Not sure if I will have time to deal with this so there's someone else here who will be trying several ways to deal with this including workarounds that won't require changes to the package. Would we great though if you'll be able to do it :)

I'm not tryin to cause you any grief.  Give me until Friday to do this.  Pretty busy around here but this needs a pretty rapid turnaround. Hang tight, on it.

**Comment by cryptomail** [comment]
Status update: I'm trying to secure an access (bearer) token to test.  I've got an internal draft PR that I'm trying to get to work locally before I push any code.

**Comment by cryptomail** [comment]
All endpoints need to be manually tested and accounted for before I flip this out of Draft.
Then I'll ensure there are commensurate betamax tests as well.

**Comment by cryptomail** [comment]
https://github.com/facetoe/zenpy/pull/660 does appear to be effective :)

**Comment by ben-lorisai** [comment]
@cryptomail that's awesome! Thanks!!
