### ISSUE TITLE
Unexpected KeyError when creating new JIRA link.

### ISSUE THREAD

**Issue by alsmith** [facetoe/zenpy#662]
I'm trying to add a new link from a Zendesk ticket to a JIRA issue.

```
link = zenpy.lib.api_objects.Link(ticket_id=ticket.id, issue_id=issue.id, issue_key=issue.key)
result = zendeskClient.jira_links.create(link)
```

This does actually create a new link in the ticket, unfortunately the python code returns the following error. Using zenpy 2.0.54.

```
Traceback (most recent call last):
  File "link.py", line 51, in <module>
    sys.exit(main())
  File "link.py", line 46, in main
    result = zendeskClient.jira_links.create(link)
  File ".env/lib/python3.7/site-packages/zenpy/lib/api.py", line 614, in create
    return CRUDRequest(self).post(api_objects, **kwargs)
  File ".env/lib/python3.7/site-packages/zenpy/lib/request.py", line 82, in post
    return self.api._post(url, payload)
  File ".env/lib/python3.7/site-packages/zenpy/lib/api.py", line 157, in _post
    return self._process_response(response)
  File ".env/lib/python3.7/site-packages/zenpy/lib/api.py", line 293, in _process_response
    r = handler(self, object_mapping).build(response)
  File ".env/lib/python3.7/site-packages/zenpy/lib/response.py", line 140, in build
    return JiraLinkGenerator(self, response_json, response)
  File ".env/lib/python3.7/site-packages/zenpy/lib/generator.py", line 362, in __init__
    object_type='links')
  File ".env/lib/python3.7/site-packages/zenpy/lib/generator.py", line 186, in __init__
    self.values = response_objects or self.process_page() or None
  File ".env/lib/python3.7/site-packages/zenpy/lib/generator.py", line 191, in process_page
    return response_objects[as_plural(self.object_type)]
KeyError: 'links'
```

**Comment by cryptomail** [comment]
Welp looks like I'll have to analyze this :) Thanks for your report.  I don't like crashbugs...I'll try to dip it in sugar and eat it :) Give me a few days.

**Comment by alsmith** [comment]
Let me know if I can help in any way.

**Comment by cryptomail** [comment]
> Let me know if I can help in any way.

All good, I'll likely reproduce it locally and trace it back to the call and the missing/incorrect nodes in the response JSON. Bummer it wasn't tested.  I've been on a campaign of adding tests (real integration tests) for all endpoints.  If and when I find the root cause of this, likely I'll ensure it's codified in a test.

**Comment by cryptomail** [comment]
Formally starting investigation:
From API specification perspective, let's look at https://developer.zendesk.com/api-reference/ticketing/jira/links/#create-link
The purported response has the following (gif) structure:
<img width="782" alt="Screenshot 2024-11-06 at 9 35 22 AM" src="https://github.com/user-attachments/assets/a9d162cf-0959-476f-a73b-7d133d0dfb89">
It does appear that a pluralization error is the root cause, at surface value.
That's where I'll start my trace, as the code is complaining about missing PLURAL ```links``` when ```link``` is the purported result set.

**Comment by cryptomail** [comment]
@alsmith Do you want to try https://github.com/facetoe/zenpy/pull/664 and see if it works....it does seem to work for me :)

**Comment by cryptomail** [comment]
Sorry just pushed latest changes to branch.  AND ADDED TEST!!!
