### ISSUE TITLE
Issue with created_greater_than being ignored in zenpy.search?

### ISSUE THREAD

**Issue by TheFoolInRed** [facetoe/zenpy#71]
Loving zenpy, this has helped make a lot of sense of this to me. That said, am a bit of a noob here, and having a devil of a time figuring out what's going on. I'm trying to setup an export that'll pull all of the ticket data from the past day. 

```
yesterday = datetime.now() - timedelta(days=1)

from zenpy import Zenpy
zenpy = Zenpy(**creds)

for ticket in zenpy.search("test", type="ticket", created_greater_than=(yesterday)):
    print(ticket.id)
    id = ticket.id
    subj = ticket.subject
    created = ticket.created_at
    for comment in zenpy.tickets.comments(ticket.id):
        body = comment.body
```

This works, but it completely ignores the created_greater_than part and starts pulling every that has the string "test"

Ideally my zenpy.search would just be 
```
for ticket in zenpy.search(created_greater_than=(yesterday)):
```
but that returns Invalid search: Please provide a valid search query which might be part of the problem. Any idea what's going wrong? I've also tried this from the documentation guide, but different error there

```
for ticket in zenpy.search(type='ticket', created_between=(yesterday, today)):
```
Returns: zenpy.lib.exception.ZenpyException: *_between requires a list!

Any idea what's going on with datetime and zenpy?

**Comment by facetoe** [comment]
HI @TheFoolInRed, yes the SearchEndpoint is currently a bit broken when it comes to `datetime` objects (see also #69) and I hope to fix this on the weekend. In the meantime you can workaround the issue by converting your `datetime` objects before passing to Zenpy, eg:

```python
yesterday = datetime.datetime.now() - datetime.timedelta(days=1)
for ticket in zenpy.search(type='ticket', created_after=yesterday.strftime("%Y-%m-%d")):
    print ticket
```
Note the use of `created_after` instead of `greater_than`. When talking about time `*_after` and `*_before` are the correct keywords to use. I'll update the docs to make that a bit clearer. 

With the second error, this is caused by passing a tuple: `created_between=(yesterday, today)` instead of a list: `created_between=[yesterday, today]`, however it really shouldn't matter so I'll fix that method to accept either.

Hope this helps!

**Comment by TheFoolInRed** [comment]
Whew, I'm still fairly new to python so I'm glad I'm not going crazy. Thank you very much for the help, zenpy has been very helpful.

**Comment by facetoe** [comment]
No worries!
